sonar.projectKey=souryadeeprc
sonar.projectName=income-tax-calculator
sonar.javascript.lcov.reportPaths=coverage/lcov-report/index.html
sonar.host.url=https://sonarcloud.io
sonar.organization=Souryadeep-Roy-Chowdhury
sonar.branch.name=develop   # <-- Add this line to specify the default branch
sonar.login=your_sonar_token