sonar.projectKey=souryadeepRC_income-tax-calculator
sonar.organization=souryadeeprc
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.tests=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx
sonar.scm.provider=git
