export const UPDATE_INCOME_DETAILS: string = "UPDATE_INCOME_DETAILS";
export const UPDATE_TAX_DETAILS: string = "UPDATE_TAX_DETAILS";
export const MODIFY_INCOME_DETAILS: string = "MODIFY_INCOME_DETAILS";
