export const UPDATE_INCOME_DETAILS = "UPDATE_INCOME_DETAILS";

export const EDIT_INCOME_ENTRY = "EDIT_INCOME_ENTRY";
export const DELETE_INCOME_ENTRY = "DELETE_INCOME_ENTRY";
export const RESET_EDIT_INCOME_ENTRY = "RESET_EDIT_INCOME_ENTRY";
export const SAVE_INCOME_DETAILS = "SAVE_INCOME_DETAILS";
export const DELETE_INCOME_DETAILS = "DELETE_INCOME_DETAILS";

export const LOAD_INCOME_DETAILS: string = "LOAD_INCOME_DETAILS";
