export const UPDATE_INCOME_DETAILS: string = "UPDATE_INCOME_DETAILS";

export const EDIT_INCOME_ENTRY: string = "EDIT_INCOME_ENTRY";
export const RESET_EDIT_INCOME_ENTRY: string = "RESET_EDIT_INCOME_ENTRY";
export const SAVE_INCOME_DETAILS: string = "SAVE_INCOME_DETAILS";
export const DELETE_INCOME_DETAILS: string = "DELETE_INCOME_DETAILS";
