export const UPDATE_SECTION_24_DEDUCTION = "UPDATE_SECTION_24_DEDUCTION";

export const EDIT_RENT_ENTRY = "EDIT_RENT_ENTRY";
export const SAVE_RENT_ENTRY = "SAVE_RENT_ENTRY";
export const DELETE_RENT_ENTRY = "DELETE_RENT_ENTRY";
export const RESET_EDIT_RENT_ENTRY = "RESET_EDIT_RENT_ENTRY";
export const SET_RENT_DEDUCTED_AMOUNT = "SET_RENT_DEDUCTED_AMOUNT";

export const EDIT_80C_ENTRY = "EDIT_80C_ENTRY";
export const SAVE_80C_ENTRY = "SAVE_80C_ENTRY";
export const DELETE_80C_ENTRY = "DELETE_80C_ENTRY";
export const RESET_EDIT_80C_ENTRY = "RESET_EDIT_80C_ENTRY";

export const EDIT_CHAPTER_VI_ENTRY = "EDIT_CHAPTER_VI_ENTRY";
export const SAVE_CHAPTER_VI_ENTRY = "SAVE_CHAPTER_VI_ENTRY";
export const DELETE_CHAPTER_VI_ENTRY = "DELETE_CHAPTER_VI_ENTRY";
export const RESET_EDIT_CHAPTER_VI_ENTRY = "RESET_EDIT_CHAPTER_VI_ENTRY";

export const LOAD_DEDUCTION: string = "LOAD_DEDUCTION";
