export const UPDATE_RENT_DEDUCTION: string = "UPDATE_RENT_DEDUCTION";
export const UPDATE_SECTION_24_DEDUCTION: string =
  "UPDATE_SECTION_24_DEDUCTION";
export const UPDATE_80C_DEDUCTION: string = "UPDATE_80C_DEDUCTION";
export const UPDATE_CHAPTER_6_DEDUCTION: string = "UPDATE_CHAPTER_6_DEDUCTION";
